### ISSUE TITLE
Error since update to Version 12.0.2 from 11.something

### ISSUE THREAD

**Issue by shortyxs** [lochmueller/calendarize#680]
Hello and thank you for this amzing Plugin.
I'm currently using it to create a broadcast schedule for a webradio station. While we are stting up the new installation, I'm running into an error that does not allow me to edit any entry nor can I add one.

Oops, an error occurred!
Too few arguments to function HDNET\Calendarize\Service\TimeTableService::__construct(), 0 passed in /www/htdocs/w01ba48c/typo310/typo3_src-10.4.26/typo3/sysext/core/Classes/Utility/GeneralUtility.php on line 3512 and exactly 1 expected

Detailed Error log
`Core: Exception handler (WEB): Uncaught TYPO3 Exception: Too few arguments to function HDNET\Calendarize\Service\TimeTableService::__construct(), 0 passed in /www/htdocs/w01ba48c/typo310/typo3_src-10.4.26/typo3/sysext/core/Classes/Utility/GeneralUtility.php on line 3512 and exactly 1 expected | ArgumentCountError thrown in file /www/htdocs/w01ba48c/typo310/public/typo3conf/ext/calendarize/Classes/Service/TimeTableService.php in line 34. Requested URL: http://test.radio-zoom.de/typo3/index.php?route=%%2Frecord%%2Fedit&token=--AnonymizedToken--&edit%%5Btx_calendarize_domain_model_event%%5D%%5B5%%5D=edit&returnUrl=%%2Ftypo3%%2Findex.php%%3Froute%%3D%%252Fmodule%%252Fweb%%252Flist%%26token%%3Dbbdd38d133a404be89dc2a8b4bfdee53c63781fc%%26id%%3D98
`
Autoloader is Version 7.3.5
Calendarize News is Version 6.2.0

Also it seems to break my relative Date Display. For Example I want to have a List of todays Events. It now Displays all events starting with todays events.

Any help is much appreciated.

**Comment by shortyxs** [comment]
OK, sometimes you need to fiddle around days on a problem, than post a bug report and find the solution yourself.

On the Database check I updated the Database index and it fixed the problem. Never the less, maybe there is a problem on the Update function?
Regarding the Relative date, it is now required to specify a relative enddate as well. In the older version it was not required.

**Comment by lochmueller** [comment]
Hey @shortyxs 
the error above is a DI container problem: https://github.com/lochmueller/calendarize/blob/master/Classes/Service/TimeTableService.php#L34 A complete clear cache should resolve this problem.
Regards,
Tim

**Comment by shortyxs** [comment]
I didn't mention it but I used the celar cache function and it still appeared. I had to update the database index to fix the problem.

**Comment by lochmueller** [comment]
@shortyxs Which "clear cache function" do you use? Keep in mind, that the caches (bolts in the backend) do not invalidate the DI cache of the core. You have to use the maintenance module or via composer (I think extension installation and deinstallation also drop the cache. Perhaps also the DB compare).
Regards,
Tim

**Comment by lochmueller** [comment]
I close this issue, because it seems that the DI container cache was not cleared after the update.
